import type { CaptionCue, CaptionStyle, CaptionWord, Overlay, Timeline } from "@editor/schemas";
import { resolveFont } from "./fonts";
import { mapSegments, mapSourceRange, type MappedSegment } from "./time";

/**
 * Timeline → Advanced SubStation Alpha. The same file is burned in by FFmpeg
 * (libass) and drawn over the preview player in the browser (JASSUB), so the
 * preview and the final render match.
 */
export function timelineToAss(t: Timeline): string {
  const W = t.output.width;
  const H = t.output.height;
  const base = t.style.resolved.captions;
  const mapped = mapSegments(t.segments);

  const styles: string[] = [assStyle("Caption", base, W, H)];
  const events: string[] = [];

  if (t.captions.enabled) {
    t.captions.cues.forEach((cue, idx) => {
      let styleName = "Caption";
      let style = base;
      if (cue.styleOverride && Object.keys(cue.styleOverride).length > 0) {
        style = { ...base, ...cue.styleOverride } as CaptionStyle;
        styleName = `Caption${idx}`;
        styles.push(assStyle(styleName, style, W, H));
      }
      events.push(...cueEvents(cue, style, styleName, mapped));
    });
  }

  const textOverlays = t.overlays.filter((o): o is Extract<Overlay, { type: "text" }> => o.type === "text");
  if (textOverlays.length) {
    const hookStyle: CaptionStyle = {
      ...base,
      fontSizePx: base.fontSizePx * 0.9,
      background: { color: "#FFFFFF", opacity: 1, paddingPx: 18, radiusPx: 0 },
      textColor: "#000000",
      strokeWidthPx: 0,
      shadow: null,
      uppercase: false,
      position: { anchor: "top", offsetYPct: 12 },
    };
    styles.push(assStyle("Hook", hookStyle, W, H));
    for (const o of textOverlays) {
      const align = o.position === "top" ? 8 : o.position === "middle" ? 5 : 2;
      const color = o.color ? `\\c${assColor(o.color)}` : "";
      events.push(dialogue(1, o.outputStartMs, o.outputEndMs, "Hook", `{\\an${align}\\fad(120,120)${color}}${escapeText(o.text)}`));
    }
  }

  return [
    "[Script Info]",
    "; Generated by @editor/core — do not edit by hand",
    "ScriptType: v4.00+",
    `PlayResX: ${W}`,
    `PlayResY: ${H}`,
    "WrapStyle: 2",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.709",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    ...styles,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ...events,
    "",
  ].join("\n");
}

function assStyle(name: string, s: CaptionStyle, W: number, H: number): string {
  const k = W / 1080;
  const font = resolveFont(s.fontFamily, s.fontWeight);
  const align = s.position.anchor === "top" ? 8 : s.position.anchor === "middle" ? 5 : 2;
  const marginV = s.position.anchor === "middle" ? 0 : Math.round((s.position.offsetYPct / 100) * H);
  const bg = s.background;
  const borderStyle = bg ? 3 : 1;
  const bgColor = bg ? assColor(bg.color, bg.opacity) : assColor("#000000", 0);
  const outlineColor = bg ? bgColor : assColor(s.strokeColor);
  const outline = bg ? bg.paddingPx * k : s.strokeWidthPx * k;
  const shadowColor = s.shadow ? assColor(s.shadow.color, 0.8) : assColor("#000000", 0);
  const shadow = s.shadow ? s.shadow.offsetPx * k : 0;
  const marginH = Math.round(60 * k);
  return [
    `Style: ${name}`,
    font.assName,
    round(s.fontSizePx * k),
    assColor(s.textColor),
    assColor(s.highlightColor),
    outlineColor,
    bg ? bgColor : shadowColor,
    font.bold ? -1 : 0,
    0, 0, 0, 100, 100, 0, 0,
    borderStyle,
    round(outline),
    round(shadow),
    align,
    marginH,
    marginH,
    marginV,
    1,
  ].join(",");
}

interface MappedWord {
  word: CaptionWord;
  outStart: number;
  outEnd: number;
  segmentIndex: number;
}

function cueEvents(cue: CaptionCue, style: CaptionStyle, styleName: string, mapped: MappedSegment[]): string[] {
  // Map each word to the output; words that were cut out disappear.
  const words: MappedWord[] = [];
  for (const w of cue.words) {
    const iv = mapSourceRange(mapped, w.sourceStartMs, Math.max(w.sourceEndMs, w.sourceStartMs + 1))[0];
    if (iv) words.push({ word: w, outStart: iv.outputStartMs, outEnd: iv.outputEndMs, segmentIndex: iv.segmentIndex });
  }
  if (!words.length) return [];

  // A cue split by a cut becomes one group per segment.
  const groups: MappedWord[][] = [];
  for (const w of words) {
    const g = groups[groups.length - 1];
    if (g && g[g.length - 1]!.segmentIndex === w.segmentIndex) g.push(w);
    else groups.push([w]);
  }

  const out: string[] = [];
  for (const g of groups) {
    const seg = mapped[g[0]!.segmentIndex]!;
    const cueEndOut = mapSourceRange([seg], cue.sourceStartMs, cue.sourceEndMs)[0]?.outputEndMs ?? g[g.length - 1]!.outEnd;
    const groupEnd = Math.max(g[g.length - 1]!.outEnd, Math.min(cueEndOut, seg.outputEndMs));
    const groupStart = g[0]!.outStart;

    if (style.animation === "none") {
      out.push(dialogue(0, groupStart, groupEnd, styleName, lineText(g, style, -1)));
      continue;
    }
    for (let k = 0; k < g.length; k++) {
      const start = k === 0 ? groupStart : g[k]!.outStart;
      const end = k === g.length - 1 ? groupEnd : g[k + 1]!.outStart;
      if (end <= start) continue;
      out.push(dialogue(0, start, end, styleName, lineText(g, style, k)));
    }
  }
  return out;
}

/** Full line with per-word overrides; `active` is the word being spoken (-1 = none). */
function lineText(g: MappedWord[], s: CaptionStyle, active: number): string {
  const parts: string[] = [];
  g.forEach((mw, i) => {
    const w = mw.word;
    const raw = w.displayText ?? w.text;
    const text = escapeText(s.uppercase ? raw.toLocaleUpperCase() : raw);
    let color = s.textColor;
    let scale = 100;
    let alpha = "00";
    let anim = "";
    if (s.emphasis.enabled && w.emphasis) {
      color = s.emphasis.color;
      scale = Math.round(s.emphasis.scale * 100);
    }
    const isActive = i === active;
    switch (s.animation) {
      case "karaoke_highlight":
        if (isActive) color = s.highlightColor;
        break;
      case "pop":
        if (isActive) {
          color = s.highlightColor;
          anim = `\\fscx${scale + 25}\\fscy${scale + 25}\\t(0,120,\\fscx${scale}\\fscy${scale})`;
        }
        break;
      case "bounce":
        if (isActive) {
          color = s.highlightColor;
          anim = `\\fscx${scale - 20}\\fscy${scale - 20}\\t(0,90,\\fscx${scale + 12}\\fscy${scale + 12})\\t(90,180,\\fscx${scale}\\fscy${scale})`;
        }
        break;
      case "word_by_word":
        if (isActive) color = s.highlightColor;
        if (active >= 0 && i > active) alpha = "FF";
        break;
      case "typewriter":
        if (active >= 0 && i > active) alpha = "FF";
        break;
      case "none":
        break;
    }
    const tags = `{\\1c${assColor(color)}\\alpha&H${alpha}&\\fscx${scale}\\fscy${scale}${anim}}`;
    const sep = i === 0 ? "" : i % s.maxWordsPerLine === 0 ? "\\N" : " ";
    parts.push(`${sep}${tags}${text}`);
  });
  return parts.join("");
}

function dialogue(layer: number, startMs: number, endMs: number, style: string, text: string): string {
  return `Dialogue: ${layer},${assTime(startMs)},${assTime(Math.max(endMs, startMs + 10))},${style},,0,0,0,,${text}`;
}

/** ASS times have centisecond precision. */
export function assTime(ms: number): string {
  const cs = Math.round(ms / 10);
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  const c = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(c).padStart(2, "0")}`;
}

/** #RRGGBB[AA] (+ optional opacity) → &HAABBGGRR (ASS alpha: 00 = opaque). */
export function assColor(hex: string, opacity = 1): string {
  const h = hex.replace("#", "");
  const r = h.slice(0, 2);
  const g = h.slice(2, 4);
  const b = h.slice(4, 6);
  const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
  const alpha = Math.round((1 - a * opacity) * 255);
  return `&H${alpha.toString(16).padStart(2, "0")}${b}${g}${r}&`.toUpperCase();
}

function escapeText(s: string): string {
  return s.replace(/\\/g, "⧵").replace(/\{/g, "(").replace(/\}/g, ")").replace(/\r?\n/g, " ");
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}
